import React from "react";
import { SecSeven } from "./nft-staking-platform-developmentComp";
import { H2 } from "../../../components";

const Sec7 = () => {
  return (
    <SecSeven>
      <section className="common_spacing gray_bg">
        <div className="container">
          <div className="row">
            <div className="section-title text-center">
              <div className="sec_tit mb20">
                <div className="section-title underline mb20">
                  <H2> Advantages of NFT staking platform </H2>
                </div>
              </div>
            </div>
          </div>
          <div className="row">
            <div
              className="col-md-6 col-sm-12 col-xs-12 aos-init aos-animate"
              data-aos="fade-right"
              data-aos-delay="200"
            >
              <div className="row">
                <div className="col-md-12 col-sm-12 col-xs-12">
                  <div className="single-service text-left">
                    <div className="icon">
                      {" "}
                      <img
                        className=""
                        data-src="/images/staking/icon/money.webp"
                        // style="width:40px;"
                        src="https://www.blockchainappfactory.com/images/staking/icon/money.webp"
                      />{" "}
                    </div>
                    <h4>Rewards</h4>
                    <p>
                      The NFT staking platform will offer various rewards based
                      on the NFT assets staked in the platform.{" "}
                    </p>
                  </div>
                </div>
                <div className="col-md-12 col-sm-12 col-xs-12">
                  <div className="single-service text-left">
                    <div className="icon">
                      {" "}
                      <img
                        className=""
                        data-src="/images/staking/icon/airdrop.webp"
                        src="https://www.blockchainappfactory.com/images/staking/icon/airdrop.webp"
                      />{" "}
                    </div>
                    <h4>Airdrop</h4>
                    <p>
                      Random airdrops are available for the users to claim in
                      the NFT staking platform too keep them motivated in
                      staking.
                    </p>
                  </div>
                </div>
                <div className="col-md-12 col-sm-12 col-xs-12">
                  <div className="single-service text-left">
                    <div className="icon">
                      {" "}
                      <img
                        className=""
                        data-src="/images/staking/icon/incentive.webp"
                        src="https://www.blockchainappfactory.com/images/staking/icon/incentive.webp"
                      />{" "}
                    </div>
                    <h4>Incentives</h4>
                    <p>
                      A constant revenue will be generated by staking the NFT,
                      and the incentive will recursively appear as long as the
                      NFT is staked.{" "}
                    </p>
                  </div>
                </div>
                <div className="col-md-12 col-sm-12 col-xs-12">
                  <div className="single-service text-left">
                    <div className="icon">
                      {" "}
                      <img
                        className=""
                        data-src="/images/staking/icon/transparency.webp"
                        src="https://www.blockchainappfactory.com/images/staking/icon/transparency.webp"
                      />{" "}
                    </div>
                    <h4>Transparency</h4>
                    <p>
                      The NFT staking platform will be completely transparent to
                      the public, and this transparency will be a big help in
                      enhancing the trustability of the platform.{" "}
                    </p>
                  </div>
                </div>
              </div>
            </div>
            <div
              className="col-md-6 col-sm-12 col-xs-12 mt-30 text-center aos-init aos-animate"
              data-aos="fade-left"
              data-aos-delay="300"
            >
              {" "}
              <img
                data-src="/images/staking/img_2.webp"
                className="mt-30"
                src="https://www.blockchainappfactory.com/images/staking/img_2.webp"
              />{" "}
            </div>
          </div>
        </div>
      </section>
    </SecSeven>
  );
};

export default Sec7;
